### ISSUE TITLE
TypeError in fastavro 1.7.3

### ISSUE THREAD

**Issue by Yeqzids** [ZwickyTransientFacility/ztf-avro-alert#8]
Running the example avro using fastavro 1.7.3 leading to a TypeError:

```
>>> import fastavro
>>> with open('472263571115115000.avro', 'rb') as f:
...     freader = fastavro.reader(f)
...     for packet in freader:
...             pass
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "fastavro/_read.pyx", line 1081, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1051, in fastavro._read.file_reader.__init__
  File "fastavro/_schema.pyx", line 119, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 188, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 225, in fastavro._schema._parse_schema
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I guess this is related to issue #6 . The code runs when I downgrade fastavro to 1.6.1 or lower.

**Comment by ebellm** [comment]
Addressed with new schemas in #9, to be released soon.
